### ISSUE TITLE
Add timestamp.now function for variables

### ISSUE THREAD

**Issue by lwlee2608** [lwlee2608/http2-load-generator#6]
Example config:

```yaml
      pre-script:
        variables:
          - name: now
            function:
              type: Now 
```
